# sales/forms.py

from django import forms
from django.forms import inlineformset_factory

from inventory.models import Product

from .models import (
    Customer,
    SalesQuotation,
    SalesQuotationItem,
    Sale,
    SaleItem,
    Invoice,
    CustomerPayment,
    EnterpriseInvoice,
)


# =====================================================
# CUSTOMER FORM
# =====================================================

class CustomerForm(forms.ModelForm):
    """
    Create or update an enterprise customer.
    """

    class Meta:
        model = Customer

        fields = [
            "user",
            "customer_type",
            "full_name",
            "company_name",
            "phone",
            "email",
            "address",
            "tax_number",
            "credit_limit",
            "is_active",
        ]

        widgets = {
            "user": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "customer_type": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "full_name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Customer full name",
                }
            ),
            "company_name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Company or institution name",
                }
            ),
            "phone": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Phone number",
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Email address",
                }
            ),
            "address": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 3,
                    "placeholder": "Customer address",
                }
            ),
            "tax_number": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Tax identification number",
                }
            ),
            "credit_limit": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "min": "0",
                    "step": "0.01",
                }
            ),
            "is_active": forms.CheckboxInput(
                attrs={
                    "class": "form-check-input",
                }
            ),
        }

    def clean_credit_limit(self):
        credit_limit = self.cleaned_data.get(
            "credit_limit"
        )

        if credit_limit is not None and credit_limit < 0:
            raise forms.ValidationError(
                "Credit limit cannot be negative."
            )

        return credit_limit

    def clean(self):
        cleaned_data = super().clean()

        full_name = (
            cleaned_data.get("full_name")
            or ""
        ).strip()

        company_name = (
            cleaned_data.get("company_name")
            or ""
        ).strip()

        user = cleaned_data.get("user")

        if not full_name and not company_name and not user:
            raise forms.ValidationError(
                (
                    "Provide a full name, company name "
                    "or linked user account."
                )
            )

        return cleaned_data


# =====================================================
# SALES QUOTATION FORM
# =====================================================

class SalesQuotationForm(forms.ModelForm):
    """
    Customer-facing quotation header.

    Status is excluded because it is managed by WorkflowService.
    Quotation number and totals are generated by the service layer.
    """

    class Meta:
        model = SalesQuotation

        fields = [
            "customer",
            "business_unit",
            "order_type",
            "quotation_date",
            "valid_until",
            "discount",
            "tax",
            "notes",
        ]

        widgets = {
            "customer": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "business_unit": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "order_type": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "quotation_date": forms.DateInput(
                attrs={
                    "class": "form-control",
                    "type": "date",
                },
                format="%Y-%m-%d",
            ),
            "valid_until": forms.DateInput(
                attrs={
                    "class": "form-control",
                    "type": "date",
                },
                format="%Y-%m-%d",
            ),
            "discount": forms.NumberInput(
                attrs={
                    "class": "form-control quotation-discount",
                    "min": "0",
                    "step": "0.01",
                }
            ),
            "tax": forms.NumberInput(
                attrs={
                    "class": "form-control quotation-tax",
                    "min": "0",
                    "step": "0.01",
                }
            ),
            "notes": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 4,
                    "placeholder": (
                        "Customer requirements, delivery terms "
                        "or quotation notes..."
                    ),
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["customer"].queryset = (
            Customer.objects
            .filter(is_active=True)
            .order_by(
                "company_name",
                "full_name",
                "phone",
            )
        )

        self.fields["customer"].empty_label = (
            "Select customer"
        )

        self.fields["business_unit"].empty_label = (
            "Select business unit"
        )

        self.fields["order_type"].empty_label = (
            "Select order type"
        )

        self.fields["quotation_date"].input_formats = [
            "%Y-%m-%d",
        ]

        self.fields["valid_until"].input_formats = [
            "%Y-%m-%d",
        ]

    def clean_discount(self):
        discount = self.cleaned_data.get(
            "discount"
        )

        if discount is not None and discount < 0:
            raise forms.ValidationError(
                "Discount cannot be negative."
            )

        return discount

    def clean_tax(self):
        tax = self.cleaned_data.get(
            "tax"
        )

        if tax is not None and tax < 0:
            raise forms.ValidationError(
                "Tax cannot be negative."
            )

        return tax

    def clean(self):
        cleaned_data = super().clean()

        quotation_date = cleaned_data.get(
            "quotation_date"
        )

        valid_until = cleaned_data.get(
            "valid_until"
        )

        if (
            quotation_date
            and valid_until
            and valid_until < quotation_date
        ):
            self.add_error(
                "valid_until",
                (
                    "Valid-until date cannot be before "
                    "the quotation date."
                ),
            )

        return cleaned_data


# =====================================================
# SALES QUOTATION ITEM FORM
# =====================================================

class SalesQuotationItemForm(forms.ModelForm):
    """
    One quotation line.

    A line may use:
    - a published inventory product; or
    - a custom product/service name.
    """

    class Meta:
        model = SalesQuotationItem

        fields = [
            "product",
            "product_name",
            "quantity",
            "unit_price",
            "specifications",
        ]

        widgets = {
            "product": forms.Select(
                attrs={
                    "class": (
                        "form-select quotation-product"
                    ),
                }
            ),
            "product_name": forms.TextInput(
                attrs={
                    "class": (
                        "form-control "
                        "quotation-product-name"
                    ),
                    "placeholder": (
                        "Custom product or service"
                    ),
                }
            ),
            "quantity": forms.NumberInput(
                attrs={
                    "class": (
                        "form-control quotation-quantity"
                    ),
                    "min": "1",
                    "step": "1",
                    "value": "1",
                }
            ),
            "unit_price": forms.NumberInput(
                attrs={
                    "class": (
                        "form-control quotation-price"
                    ),
                    "min": "0",
                    "step": "0.01",
                }
            ),
            "specifications": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 2,
                    "placeholder": (
                        "Dimensions, material, color, "
                        "scope or other specifications"
                    ),
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # All products approved for sale appear
        # regardless of quotation business unit.
        self.fields["product"].queryset = (
            Product.objects
            .filter(is_published=True)
            .order_by("name")
        )

        self.fields["product"].empty_label = (
            "Select published product"
        )

        self.fields["product"].required = False
        self.fields["product_name"].required = False

    def clean(self):
        cleaned_data = super().clean()

        if cleaned_data.get("DELETE"):
            return cleaned_data

        product = cleaned_data.get("product")

        product_name = (
            cleaned_data.get("product_name")
            or ""
        ).strip()

        quantity = cleaned_data.get("quantity")
        unit_price = cleaned_data.get(
            "unit_price"
        )

        if not product and not product_name:
            raise forms.ValidationError(
                (
                    "Select a published product or enter "
                    "a custom product/service name."
                )
            )

        if quantity is not None and quantity <= 0:
            self.add_error(
                "quantity",
                (
                    "Quantity must be greater than zero."
                ),
            )

        if unit_price is not None and unit_price < 0:
            self.add_error(
                "unit_price",
                (
                    "Unit price cannot be negative."
                ),
            )

        return cleaned_data


# =====================================================
# SALES QUOTATION ITEM INLINE FORMSET
# =====================================================

SalesQuotationItemFormSet = inlineformset_factory(
    parent_model=SalesQuotation,
    model=SalesQuotationItem,
    form=SalesQuotationItemForm,
    fields=[
        "product",
        "product_name",
        "quantity",
        "unit_price",
        "specifications",
    ],
    extra=1,
    can_delete=True,
    min_num=1,
    validate_min=True,
)


# =====================================================
# LEGACY SALE FORM
# =====================================================

class SaleForm(forms.ModelForm):

    class Meta:
        model = Sale

        fields = [
            "customer",
            "warehouse",
            "quotation",
            "sale_date",
            "discount",
            "tax",
            "status",
        ]

        widgets = {
            "customer": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "warehouse": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "quotation": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "sale_date": forms.DateInput(
                attrs={
                    "class": "form-control",
                    "type": "date",
                }
            ),
            "discount": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "min": "0",
                    "step": "0.01",
                }
            ),
            "tax": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "min": "0",
                    "step": "0.01",
                }
            ),
            "status": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
        }


# =====================================================
# LEGACY SALE ITEM FORM
# =====================================================

class SaleItemForm(forms.ModelForm):

    class Meta:
        model = SaleItem

        fields = [
            "product",
            "quantity",
            "unit_price",
        ]

        widgets = {
            "product": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "quantity": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "min": "1",
                    "step": "0.01",
                }
            ),
            "unit_price": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "min": "0",
                    "step": "0.01",
                }
            ),
        }


SaleItemFormSet = inlineformset_factory(
    parent_model=Sale,
    model=SaleItem,
    form=SaleItemForm,
    extra=1,
    can_delete=True,
)


# =====================================================
# LEGACY INVOICE FORM
# =====================================================

class InvoiceForm(forms.ModelForm):

    class Meta:
        model = Invoice

        fields = [
            "sale",
            "invoice_date",
            "due_date",
            "amount_paid",
            "status",
        ]

        widgets = {
            "sale": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "invoice_date": forms.DateInput(
                attrs={
                    "class": "form-control",
                    "type": "date",
                }
            ),
            "due_date": forms.DateInput(
                attrs={
                    "class": "form-control",
                    "type": "date",
                }
            ),
            "amount_paid": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "min": "0",
                    "step": "0.01",
                }
            ),
            "status": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
        }


# =====================================================
# LEGACY CUSTOMER PAYMENT FORM
# =====================================================

class CustomerPaymentForm(forms.ModelForm):

    class Meta:
        model = CustomerPayment

        fields = [
            "invoice",
            "amount",
            "payment_method",
            "payment_date",
            "reference",
            "notes",
        ]

        widgets = {
            "invoice": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "amount": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "min": "0.01",
                    "step": "0.01",
                }
            ),
            "payment_method": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "payment_date": forms.DateInput(
                attrs={
                    "class": "form-control",
                    "type": "date",
                }
            ),
            "reference": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": (
                        "Transaction or payment reference"
                    ),
                }
            ),
            "notes": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 3,
                }
            ),
        }

    def clean_amount(self):
        amount = self.cleaned_data.get("amount")

        if amount is not None and amount <= 0:
            raise forms.ValidationError(
                "Payment amount must be greater than zero."
            )

        return amount


class EnterpriseInvoiceDraftForm(forms.ModelForm):
    class Meta:
        model = EnterpriseInvoice
        fields = ["due_date"]
        widgets = {
            "due_date": forms.DateInput(attrs={"class": "form-control", "type": "date"}),
        }

    def clean_due_date(self):
        due_date = self.cleaned_data["due_date"]
        from django.utils import timezone
        if due_date < timezone.localdate():
            raise forms.ValidationError("Due date cannot be in the past.")
        return due_date
