# Generated by Django 6.0.5 on 2026-06-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0002_remove_productionmachine_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_usage', to='inventory.asset')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='core.productionorder')),
            ],
        ),
    ]
