# Generated by Django 6.0.5 on 2026-06-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('core', '0002_productionmachine'),
        ('inventory', '0002_remove_productionmachine_asset_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductionOrder',
            new_name='Order',
        ),
    ]
