# Generated by Django 6.0.5 on 2026-06-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_productionorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionoutput',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='productionlabour',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='productionmachine',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='productionmaterial',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='productionlabour',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='productionmachine',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='productionmaterial',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='productionoutput',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductionLabour',
        ),
        migrations.DeleteModel(
            name='ProductionMachine',
        ),
        migrations.DeleteModel(
            name='ProductionMaterial',
        ),
        migrations.DeleteModel(
            name='ProductionOutput',
        ),
    ]
