# Generated by Django 6.0.5 on 2026-06-23 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='auth.group')),
            ],
            options={
                'unique_together': {('role', 'module')},
            },
        ),
    ]
