# Generated by Django 6.0.5 on 2026-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rolemodule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolemodule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='module',
            name='permission',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
