# Generated by Django 6.0.5 on 2026-07-06 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businessunit_enterpriseengine_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cards', to='core.businessunit'),
        ),
        migrations.AddField(
            model_name='dashboardcard',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cards', to='core.enterpriseengine'),
        ),
        migrations.AlterField(
            model_name='dashboardcard',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cards', to='core.module'),
        ),
    ]
