# Generated by Django 6.0.5 on 2026-07-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dashboardcard_business_unit_dashboardcard_engine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardcard',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='dashboardcard',
            name='engine',
        ),
    ]
