# Generated by Django 6.0.5 on 2026-07-06 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_dashboardcard_business_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('widget_type', models.CharField(choices=[('NUMBER', 'Number'), ('MONEY', 'Money'), ('PERCENT', 'Percent'), ('CHART', 'Chart'), ('TABLE', 'Table'), ('ALERT', 'Alert')], default='NUMBER', max_length=20)),
                ('data_source', models.CharField(blank=True, help_text='Example: finance.net_profit or furniture.active_jobs', max_length=150)),
                ('value_key', models.CharField(blank=True, help_text='Key returned by dashboard service', max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='primary', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_widgets', to='core.businessunit')),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_widgets', to='core.enterpriseengine')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
