# Generated by Django 6.0.5 on 2026-08-27 14:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_groupaccessprofile'),
        ('finance', '0016_finance_integrity_constraints'),
        ('orders', '0009_order_integrity_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FUNDING', 'Funding'), ('FUNDED', 'Fully funded'), ('ACTIVE', 'Job in progress'), ('SETTLEMENT', 'Investor settlement'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('estimated_job_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Approved estimate required to complete this specific job.', max_digits=18)),
                ('contract_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Approved customer quotation/contract value for this job.', max_digits=18)),
                ('wpg_capital_committed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="WPG's own money committed to this job.", max_digits=18)),
                ('actual_revenue_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Finance-synced customer revenue for this job.', max_digits=18)),
                ('actual_cost_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Finance-synced actual cost of this job.', max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_job_investments', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job_investment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('manage_job_investment', 'Can manage job investment'), ('approve_investor_agreement', 'Can approve investor agreement'), ('settle_job_investor', 'Can settle job investor')],
            },
        ),
        migrations.CreateModel(
            name='JobInvestorAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SETTLEMENT_DUE', 'Settlement due'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('committed_capital', models.DecimalField(decimal_places=2, max_digits=18)),
                ('return_model', models.CharField(choices=[('CAPITAL_ONLY', 'Return capital only'), ('FIXED_PROFIT', 'Capital + fixed profit'), ('PROFIT_SHARE', 'Capital + percentage of actual job profit')], default='CAPITAL_ONLY', max_length=20)),
                ('fixed_profit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('profit_share_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of positive ACTUAL profit of this job.', max_digits=6)),
                ('agreement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('repayment_due_date', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_job_investor_agreements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_investor_agreements', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(help_text='Use the existing Finance Counterparty identity.', on_delete=django.db.models.deletion.PROTECT, related_name='job_investor_agreements', to='finance.counterparty')),
                ('job_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_agreements', to='core.jobinvestment')),
            ],
            options={
                'ordering': ['job_investment', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobInvestorContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PLEDGED', 'Pledged'), ('RECEIVED', 'Received'), ('REVERSED', 'Reversed')], db_index=True, default='PLEDGED', max_length=20)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.jobinvestoragreement')),
                ('finance_income_declaration', models.OneToOneField(blank=True, help_text='When cash is actually received, link the confirmed Finance Income Declaration instead of creating another cash transaction.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_investor_contribution', to='finance.incomedeclaration')),
                ('job_investment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='investor_contributions', to='core.jobinvestment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_job_investor_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobInvestorSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('investor_profit_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PARTIAL', 'Partially paid'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='core.jobinvestoragreement')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_job_investor_settlements', to=settings.AUTH_USER_MODEL)),
                ('finance_debt_record', models.OneToOneField(blank=True, help_text='Repayment/payment execution remains in Finance. Link its debt/payable record here.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_investor_settlement', to='finance.debtrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobinvestment',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_job_cost__gte', 0)), name='core_job_inv_est_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='jobinvestment',
            constraint=models.CheckConstraint(condition=models.Q(('contract_value__gte', 0)), name='core_job_inv_contract_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='jobinvestment',
            constraint=models.CheckConstraint(condition=models.Q(('wpg_capital_committed__gte', 0)), name='core_job_inv_wpg_capital_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='jobinvestment',
            constraint=models.CheckConstraint(condition=models.Q(('actual_revenue_snapshot__gte', 0)), name='core_job_inv_revenue_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='jobinvestment',
            constraint=models.CheckConstraint(condition=models.Q(('actual_cost_snapshot__gte', 0)), name='core_job_inv_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='jobinvestoragreement',
            constraint=models.CheckConstraint(condition=models.Q(('committed_capital__gt', 0)), name='core_job_agreement_capital_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='jobinvestoragreement',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_profit_amount__gte', 0)), name='core_job_agreement_fixed_profit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='jobinvestoragreement',
            constraint=models.CheckConstraint(condition=models.Q(('profit_share_percent__gte', 0), ('profit_share_percent__lte', 100)), name='core_job_agreement_profit_share_0_100'),
        ),
        migrations.AddConstraint(
            model_name='jobinvestoragreement',
            constraint=models.UniqueConstraint(fields=('job_investment', 'investor'), name='core_unique_investor_per_job'),
        ),
        migrations.AddConstraint(
            model_name='jobinvestorcontribution',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='core_job_contribution_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='jobinvestorsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('principal_due__gte', 0)), name='core_job_settlement_principal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='jobinvestorsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('investor_profit_due__gte', 0)), name='core_job_settlement_profit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='jobinvestorsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='core_job_settlement_paid_nonnegative'),
        ),
    ]
