# Generated by Django 6.0.5 on 2026-08-27 15:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cleanup_order_engine_navigation'),
        ('finance', '0016_finance_integrity_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFinanceExpenseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job_investment_cost_link', to='finance.expenserequest')),
                ('job_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_expense_links', to='core.jobinvestment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobFinanceIncomeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('income_declaration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job_investment_revenue_link', to='finance.incomedeclaration')),
                ('job_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_income_links', to='core.jobinvestment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
