# Generated by Django 6.0.5 on 2026-06-12 12:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('inventory', '0002_remove_productionmachine_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountsPayable',
            new_name='Payable',
        ),
        migrations.RenameModel(
            old_name='AccountsReceivable',
            new_name='Receivable',
        ),
    ]
