# Generated by Django 6.0.5 on 2026-06-19 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_accountspayable_payable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('salary', 'Salary'), ('rent', 'Rent'), ('transport', 'Transport'), ('raw_material', 'Raw Material'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.account'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('construction', 'Construction'), ('furniture', 'Furniture'), ('service', 'Service'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='payable',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile_money', 'Mobile Money')], max_length=30),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account')),
            ],
        ),
    ]
