# Generated by Django 6.0.5 on 2026-07-30 20:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_receivable_order_alter_receivable_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20)),
                ('business_unit', models.CharField(blank=True, choices=[('', 'Shared / Enterprise'), ('FURNITURE', 'Furniture & Manufacturing'), ('CONSTRUCTION', 'Construction & Built Environment'), ('AGRICULTURE', 'Agriculture / Poultry'), ('MARKETPLACE', 'Marketplace')], db_index=True, max_length=30)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('source_key', models.CharField(blank=True, help_text='Idempotency key for the business event being posted.', max_length=180, null=True, unique=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='finance.journalentry')),
            ],
            options={
                'ordering': ['-entry_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=60, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=100)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('applied_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('PARTIALLY_APPLIED', 'Partially Applied'), ('APPLIED', 'Applied'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_advances', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_customer_advances', to=settings.AUTH_USER_MODEL)),
                ('receipt_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_customer_advance', to='finance.journalentry')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], db_index=True, max_length=20)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('business_unit', models.CharField(blank=True, choices=[('', 'Shared / Enterprise'), ('FURNITURE', 'Furniture & Manufacturing'), ('CONSTRUCTION', 'Construction & Built Environment'), ('AGRICULTURE', 'Agriculture / Poultry'), ('MARKETPLACE', 'Marketplace')], db_index=True, max_length=30)),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('is_control_account', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.ledgeraccount')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.ledgeraccount')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status', 'entry_date'], name='fin_gl_entry_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='fin_gl_entry_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeradvance',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='fin_unique_advance_source'),
        ),
        migrations.AddConstraint(
            model_name='customeradvance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fin_advance_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='customeradvance',
            constraint=models.CheckConstraint(condition=models.Q(('applied_amount__gte', 0)), name='fin_advance_applied_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customeradvance',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0)), name='fin_advance_refunded_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['account_type', 'business_unit', 'is_active'], name='fin_gl_acct_type_unit_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='fin_gl_line_one_side_positive'),
        ),
    ]
