# Generated by Django 6.0.5 on 2026-08-21 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_journalentry_customeradvance_ledgeraccount_and_more'),
        ('inventory', '0009_alter_category_options_alter_product_options_and_more'),
        ('sales', '0005_alter_customer_options_alter_salesquotation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('INSTITUTION', 'Institution')], default='INDIVIDUAL', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(help_text='Rwanda telephone number, for example 0788123456 or +250788123456.', max_length=16)),
                ('phone_identity', models.CharField(editable=False, help_text='Normalized Rwanda national number used for duplicate detection.', max_length=9, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('bank_account_identity', models.CharField(blank=True, editable=False, help_text='Normalized bank account used for duplicate detection.', max_length=100, null=True, unique=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_supplier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_counterparty', to='inventory.supplier')),
                ('sales_customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_counterparty', to='sales.customer')),
            ],
            options={
                'verbose_name_plural': 'counterparties',
                'ordering': ['name', 'phone'],
            },
        ),
    ]
