# Generated by Django 6.0.5 on 2026-08-21 09:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_add_counterparty_identity'),
        ('inventory', '0009_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=60, unique=True)),
                ('direction', models.CharField(choices=[('THEY_OWE_US', 'They owe WPG money'), ('WE_OWE_THEM', 'WPG owes them money')], db_index=True, max_length=20)),
                ('business_unit', models.CharField(choices=[('GENERAL', 'WPG General'), ('FURNITURE', 'Furniture & Manufacturing'), ('CONSTRUCTION', 'Construction'), ('AGRICULTURE', 'Agriculture / Poultry'), ('MARKETPLACE', 'Marketplace')], db_index=True, default='GENERAL', max_length=30)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_records', to='finance.counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_counterparty_debts', to=settings.AUTH_USER_MODEL)),
                ('payable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_debt_record', to='finance.payable')),
                ('receivable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_debt_record', to='finance.receivable')),
            ],
            options={
                'ordering': ['-transaction_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DebtLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Product or service supplied in this transaction.', max_length=300)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=14)),
                ('unit', models.CharField(default='piece', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_debt_lines', to='inventory.product')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.debtrecord')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['counterparty', 'direction', 'status'], name='fin_debt_party_dir_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='fin_debt_line_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='debtline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='fin_debt_line_price_nonnegative'),
        ),
    ]
