# Generated by Django 6.0.5 on 2026-08-21 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_counterparty_debt_records'),
        ('inventory', '0009_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtline',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_debt_lines', to='inventory.asset'),
        ),
        migrations.AddField(
            model_name='debtline',
            name='item_type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('RAW_MATERIAL', 'Raw material'), ('ASSET', 'Asset'), ('SERVICE', 'Service'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='debtline',
            name='raw_material',
            field=models.ForeignKey(blank=True, help_text='Legacy raw material. New raw materials should normally use an Inventory Product.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_debt_lines', to='inventory.rawmaterial'),
        ),
        migrations.AddConstraint(
            model_name='debtline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', True), ('item_type', 'PRODUCT'), ('product__isnull', False), ('raw_material__isnull', True)), models.Q(('asset__isnull', True), ('item_type', 'RAW_MATERIAL'), ('product__isnull', True), ('raw_material__isnull', False)), models.Q(('asset__isnull', False), ('item_type', 'ASSET'), ('product__isnull', True), ('raw_material__isnull', True)), models.Q(('asset__isnull', True), ('item_type__in', ['SERVICE', 'OTHER']), ('product__isnull', True), ('raw_material__isnull', True)), _connector='OR'), name='fin_debt_line_item_source_valid'),
        ),
    ]
