from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Employee", "0012_alter_leave_options"),
        ("finance", "0012_obligation_catalog"),
    ]

    operations = [
        migrations.AddField(model_name="income", name="received_from", field=models.ForeignKey(blank=True, help_text="Person, company or institution that paid WPG.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="income_records", to="finance.counterparty")),
        migrations.AddField(model_name="income", name="reference", field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name="income", name="notes", field=models.TextField(blank=True)),
        migrations.AddField(model_name="income", name="business_unit", field=models.CharField(choices=[("FURNITURE", "Furniture & Manufacturing"), ("CONSTRUCTION", "Construction & Built Environment"), ("AGRICULTURE", "Agriculture & Poultry"), ("MARKETPLACE", "Marketplace"), ("SHARED", "Shared services")], default="SHARED", max_length=30)),
        migrations.AddField(model_name="expense", name="paid_to", field=models.ForeignKey(blank=True, help_text="Person, company, employee or institution paid by WPG.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="expense_records", to="finance.counterparty")),
        migrations.AddField(model_name="expense", name="reference", field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name="expense", name="notes", field=models.TextField(blank=True)),
        migrations.AddField(model_name="expense", name="business_unit", field=models.CharField(choices=[("FURNITURE", "Furniture & Manufacturing"), ("CONSTRUCTION", "Construction & Built Environment"), ("AGRICULTURE", "Agriculture & Poultry"), ("MARKETPLACE", "Marketplace"), ("SHARED", "Shared services")], default="SHARED", max_length=30)),
        migrations.CreateModel(
            name="IncomeDeclaration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("declaration_number", models.CharField(editable=False, max_length=32, unique=True)),
                ("business_unit", models.CharField(choices=[("FURNITURE", "Furniture & Manufacturing"), ("CONSTRUCTION", "Construction & Built Environment"), ("AGRICULTURE", "Agriculture & Poultry"), ("MARKETPLACE", "Marketplace"), ("SHARED", "Shared services")], max_length=30)),
                ("title", models.CharField(max_length=200)),
                ("source_type", models.CharField(choices=[("SALE", "Sale"), ("SERVICE", "Service"), ("INVESTMENT", "Owner investment"), ("LOAN", "Loan received"), ("GRANT", "Grant"), ("RENT", "Rental income"), ("INTEREST", "Interest income"), ("OTHER", "Other")], max_length=30)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("receipt_method", models.CharField(choices=[("cash", "Cash"), ("bank", "Bank"), ("mobile_money", "Mobile Money")], max_length=30)),
                ("receipt_date", models.DateField()),
                ("reference", models.CharField(max_length=100)),
                ("proof_document", models.FileField(blank=True, upload_to="finance/income_declarations/%Y/%m/")),
                ("notes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Awaiting unit manager"), ("UNIT_APPROVED", "Awaiting Finance confirmation"), ("FINANCE_CONFIRMED", "Confirmed and posted"), ("RETURNED", "Returned for correction"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled")], db_index=True, default="DRAFT", max_length=30)),
                ("unit_approved_at", models.DateTimeField(blank=True, null=True)),
                ("unit_comment", models.TextField(blank=True)),
                ("finance_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("finance_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="confirmed_income_declarations", to="finance.account")),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="income_declarations", to="Employee.department")),
                ("finance_confirmed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="finance_confirmed_income_declarations", to=settings.AUTH_USER_MODEL)),
                ("posted_income", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_declaration", to="finance.income")),
                ("received_from", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="income_declarations", to="finance.counterparty")),
                ("recorded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="income_declarations", to=settings.AUTH_USER_MODEL)),
                ("related_sale", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="finance_income_declarations", to="sales.sale")),
                ("unit_approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="unit_approved_income_declarations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="ExpenseRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_number", models.CharField(editable=False, max_length=32, unique=True)),
                ("business_unit", models.CharField(choices=[("FURNITURE", "Furniture & Manufacturing"), ("CONSTRUCTION", "Construction & Built Environment"), ("AGRICULTURE", "Agriculture & Poultry"), ("MARKETPLACE", "Marketplace"), ("SHARED", "Shared services")], default="SHARED", max_length=30)),
                ("request_type", models.CharField(choices=[("DIRECT_PAYMENT", "Direct payment"), ("CASH_ADVANCE", "Cash advance"), ("REIMBURSEMENT", "Employee reimbursement")], default="DIRECT_PAYMENT", max_length=30)),
                ("title", models.CharField(max_length=200)),
                ("expense_type", models.CharField(choices=[("salary", "Salary"), ("rent", "Rent"), ("transport", "Transport"), ("raw_material", "Raw Material"), ("maintenance", "Maintenance"), ("other", "Other")], max_length=50)),
                ("purpose", models.TextField()),
                ("amount_requested", models.DecimalField(decimal_places=2, max_digits=15)),
                ("needed_by", models.DateField()),
                ("urgency", models.CharField(choices=[("NORMAL", "Normal"), ("URGENT", "Urgent"), ("CRITICAL", "Critical")], default="NORMAL", max_length=20)),
                ("supporting_document", models.FileField(blank=True, upload_to="finance/expense_requests/%Y/%m/")),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Awaiting line manager"), ("MANAGER_APPROVED", "Awaiting accountant"), ("FINANCE_VERIFIED", "Awaiting finance manager"), ("FINANCE_APPROVED", "Awaiting company director"), ("FINAL_APPROVED", "Ready for payment"), ("PAID", "Paid"), ("ACCOUNTABILITY_PENDING", "Awaiting accountability"), ("COMPLETED", "Completed"), ("RETURNED", "Returned for correction"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled")], db_index=True, default="DRAFT", max_length=30)),
                ("funds_available", models.BooleanField(blank=True, null=True)),
                ("balance_checked", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("manager_approved_at", models.DateTimeField(blank=True, null=True)),
                ("manager_comment", models.TextField(blank=True)),
                ("accountant_verified_at", models.DateTimeField(blank=True, null=True)),
                ("accountant_comment", models.TextField(blank=True)),
                ("finance_approved_at", models.DateTimeField(blank=True, null=True)),
                ("finance_comment", models.TextField(blank=True)),
                ("director_approved_at", models.DateTimeField(blank=True, null=True)),
                ("director_comment", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("amount_paid", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("payment_method", models.CharField(blank=True, choices=[("cash", "Cash"), ("bank", "Bank"), ("mobile_money", "Mobile Money")], max_length=30)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("accountability_notes", models.TextField(blank=True)),
                ("accountability_document", models.FileField(blank=True, upload_to="finance/accountability/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accountant_verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="accountant_verified_expense_requests", to=settings.AUTH_USER_MODEL)),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="expense_requests", to="Employee.department")),
                ("director_approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="director_approved_expense_requests", to=settings.AUTH_USER_MODEL)),
                ("expense", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_request", to="finance.expense")),
                ("finance_approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="finance_approved_expense_requests", to=settings.AUTH_USER_MODEL)),
                ("manager_approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="manager_approved_expense_requests", to=settings.AUTH_USER_MODEL)),
                ("paid_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="paid_expense_requests", to=settings.AUTH_USER_MODEL)),
                ("payee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="expense_requests", to="finance.counterparty")),
                ("proposed_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="proposed_expense_requests", to="finance.account")),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="expense_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-created_at",),
                "permissions": (("submit_expenserequest", "Can submit expense request"), ("manager_approve_expenserequest", "Can approve expense request as line manager"), ("verify_expenserequest", "Can verify expense request as accountant"), ("finance_approve_expenserequest", "Can approve expense request as finance manager"), ("director_approve_expenserequest", "Can give final approval to expense request"), ("pay_expenserequest", "Can pay an approved expense request")),
            },
        ),
    ]
