# Generated by Django 6.0.5 on 2026-06-18 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_remove_employee_job_title'),
        ('furniture', '0004_quotation_status'),
        ('inventory', '0005_warehouse_rawmaterial_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionlabour',
            old_name='production_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='productionmachine',
            old_name='production_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='productionmaterial',
            old_name='production_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='productionoutput',
            old_name='production_order',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterial',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='actual_end_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productionmachine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productionmachine',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='worker',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='produced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotes', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='machine_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_quotes', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_furniture_orders', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_furniture_orders', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('quotation_pending', 'Quotation Pending'), ('quotation_approved', 'Quotation Approved'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='productionmachine',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.asset'),
        ),
        migrations.AlterField(
            model_name='productionmachine',
            name='hourly_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionmachine',
            name='hours_used',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionmaterial',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionoutput',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
