# Generated by Django 6.0.5 on 2026-07-03 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_remove_leave_approved_leave_status_leave_updated_at'),
        ('furniture', '0005_rename_production_order_productionlabour_order_and_more'),
        ('inventory', '0006_product_image_product_is_featured_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('RESTOCK', 'Restock Existing Product'), ('CUSTOMER_CUSTOM', 'Customer Custom Order'), ('NEW_PRODUCT', 'New Product Development')], default='RESTOCK', max_length=30)),
                ('quantity_to_produce', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUOTATION_PENDING', 'Quotation Pending'), ('QUOTATION_APPROVED', 'Quotation Approved'), ('IN_PRODUCTION', 'In Production'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_production_jobs', to='Employee.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_jobs', to='Employee.employee')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_job', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
        ),
    ]
