# Generated by Django 6.0.5 on 2026-07-03 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0006_productionjob'),
        ('inventory', '0006_product_image_product_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionlabour',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productionmachine',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productionmaterial',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productionoutput',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='stockreservation',
            name='order',
        ),
        migrations.AddField(
            model_name='productionlabour',
            name='production_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labours', to='furniture.productionjob'),
        ),
        migrations.AddField(
            model_name='productionmachine',
            name='production_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='furniture.productionjob'),
        ),
        migrations.AddField(
            model_name='productionmaterial',
            name='production_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='furniture.productionjob'),
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='production_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='furniture.productionjob'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='production_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='furniture.productionjob'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='production_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='furniture.productionjob'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='inventory.product'),
        ),
    ]
