# Generated by Django 6.0.5 on 2026-07-03 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_remove_leave_approved_leave_status_leave_updated_at'),
        ('furniture', '0007_remove_productionlabour_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionoutput',
            old_name='date',
            new_name='produced_at',
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='production_outputs/'),
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='furniture.order'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='other_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionoutput',
            name='produced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee'),
        ),
    ]
