# Generated by Django 6.0.5 on 2026-07-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0008_rename_date_productionoutput_produced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionjob',
            name='job_type',
            field=models.CharField(choices=[('RESTOCK', 'Restock Existing Product'), ('CUSTOMER_CUSTOM', 'Customer Custom Order'), ('NEW_PRODUCT', 'New Product Development'), ('BACKORDER', 'Ecommerce Backorder')], default='RESTOCK', max_length=30),
        ),
    ]
