# Generated by Django 6.0.5 on 2026-07-08 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_remove_leave_approved_leave_status_leave_updated_at'),
        ('furniture', '0009_alter_productionjob_job_type'),
        ('inventory', '0006_product_image_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Legacy Furniture Order', 'verbose_name_plural': 'Legacy Furniture Orders'},
        ),
        migrations.AlterModelOptions(
            name='productionjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='productionoutput',
            name='order',
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='legacy_order',
            field=models.ForeignKey(blank=True, help_text='Legacy furniture order. Use production_job instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='furniture.order'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furniture_boms', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productionjob',
            name='status',
            field=models.CharField(choices=[('QUOTATION', 'Quotation'), ('APPROVED', 'Approved'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('MATERIAL_RESERVED', 'Material Reserved'), ('IN_PRODUCTION', 'In Production'), ('QUALITY_CHECK', 'Quality Check'), ('FINISHED_GOODS', 'Finished Goods'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='QUOTATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Optional margin percentage', max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='production_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='furniture.productionjob'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('USED', 'Used'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('MATERIAL_SHORTAGE', 'Material Shortage'), ('MACHINE_BREAKDOWN', 'Machine Breakdown'), ('LABOUR_ABSENCE', 'Labour Absence'), ('QUALITY_PROBLEM', 'Quality Problem'), ('OTHER', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='furniture.productionjob')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee')),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='furniture.productionjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0, help_text='Quality score from 0 to 100')),
                ('remarks', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee')),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='furniture.productionjob')),
            ],
        ),
    ]
