# Generated by Django 6.0.5 on 2026-07-10 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_remove_leave_approved_leave_status_leave_updated_at'),
        ('furniture', '0010_alter_order_options_alter_productionjob_options_and_more'),
        ('inventory', '0006_product_image_product_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('task_type', models.CharField(choices=[('DESIGN', 'Design'), ('MEASUREMENT', 'Measurement'), ('CUTTING', 'Cutting'), ('PLANING', 'Planing'), ('THICKNESSING', 'Thicknessing'), ('SHAPING', 'Shaping'), ('JOINERY', 'Joinery'), ('ASSEMBLY', 'Assembly'), ('SANDING', 'Sanding'), ('PAINTING', 'Painting'), ('FINISHING', 'Finishing'), ('DRYING', 'Drying'), ('UPHOLSTERY', 'Upholstery'), ('QUALITY_CHECK', 'Quality Check'), ('PACKAGING', 'Packaging'), ('DELIVERY', 'Delivery'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Order of execution inside the production job.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Task completion percentage from 0 to 100.')),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_tasks', to='Employee.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_tasks', to='Employee.employee')),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='furniture.productionjob')),
            ],
            options={
                'ordering': ['production_job', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_task_checklists', to='Employee.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='furniture.productiontask')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MachineUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('hours_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='furniture_task_usage_logs', to='inventory.asset')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_usage_logs', to='Employee.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_usage_logs', to='furniture.productiontask')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_task_records', to='Employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='Employee.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='furniture.productiontask')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('STARTED', 'Started'), ('PAUSED', 'Paused'), ('RESUMED', 'Resumed'), ('PROGRESS_UPDATED', 'Progress Updated'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NOTE', 'Note')], max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_task_logs', to='Employee.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='furniture.productiontask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productiontask',
            index=models.Index(fields=['production_job', 'status'], name='furniture_p_product_6a3e11_idx'),
        ),
        migrations.AddIndex(
            model_name='productiontask',
            index=models.Index(fields=['assigned_to', 'status'], name='furniture_p_assigne_9126fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='productiontask',
            constraint=models.UniqueConstraint(fields=('production_job', 'sequence'), name='unique_task_sequence_per_production_job'),
        ),
    ]
