# Generated by Django 6.0.5 on 2026-07-13 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0012_productiontaskprogress'),
        ('inventory', '0006_product_image_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterial',
            options={'ordering': ['product__name', 'raw_material__name'], 'verbose_name': 'Bill of Material', 'verbose_name_plural': 'Bills of Materials'},
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_bom_items', to='inventory.rawmaterial'),
        ),
        migrations.AddIndex(
            model_name='billofmaterial',
            index=models.Index(fields=['product', 'raw_material'], name='furniture_bom_product_material_idx'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.UniqueConstraint(fields=('product', 'raw_material'), name='unique_material_per_furniture_product'),
        ),
    ]
