# Generated by Django 6.0.5 on 2026-07-13 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0013_alter_billofmaterial_options_and_more'),
        ('inventory', '0006_product_image_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='furniture_boms', to='inventory.product'),
            preserve_default=False,
        ),
    ]
