# Generated by Django 6.0.5 on 2026-07-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0014_alter_billofmaterial_product'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billofmaterial',
            new_name='furn_bom',
            old_name='furniture_bom_product_material_idx',
        ),
    ]
