# Generated by Django 6.0.5 on 2026-07-15 16:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0015_rename_furniture_bom_product_material_idx_furn_bom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overhead_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Overhead percentage applied to direct production cost.', max_digits=6)),
                ('wastage_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Default material wastage percentage.', max_digits=6)),
                ('default_transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('default_other_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('default_labour_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('default_machine_hourly_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=6)),
                ('target_profit_margin', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=6)),
                ('currency', models.CharField(default='RWF', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Production Settings',
                'verbose_name_plural': 'Production Settings',
            },
        ),
    ]
