# Generated by Django 6.0.5 on 2026-07-16 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_remove_leave_approved_leave_status_leave_updated_at'),
        ('furniture', '0016_productionsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(choices=[('DIMENSION', 'Incorrect Dimension'), ('MATERIAL', 'Material Defect'), ('ASSEMBLY', 'Assembly Defect'), ('SURFACE', 'Surface Defect'), ('PAINT', 'Painting / Finishing Defect'), ('STRUCTURAL', 'Structural Defect'), ('PACKAGING', 'Packaging Defect'), ('OTHER', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], default='MINOR', max_length=20)),
                ('description', models.TextField()),
                ('affected_quantity', models.PositiveIntegerField(default=1)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REWORK_REQUIRED', 'Rework Required'), ('UNDER_REWORK', 'Under Rework'), ('RESOLVED', 'Resolved'), ('ACCEPTED', 'Accepted with Deviation'), ('SCRAPPED', 'Scrapped')], default='OPEN', max_length=30)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='quality/defects/%Y/%m/')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReworkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rework_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('instructions', models.TextField()),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rework_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('completion_note', models.TextField(blank=True)),
                ('completion_image', models.ImageField(blank=True, null=True, upload_to='quality/rework/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='qualityinspection',
            options={'ordering': ['-inspected_at']},
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quality_inspections', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='quality/inspections/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='inspection_type',
            field=models.CharField(choices=[('IN_PROCESS', 'In-process Inspection'), ('FINAL', 'Final Inspection'), ('RE_INSPECTION', 'Re-inspection')], default='FINAL', max_length=20),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='quantity_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='quantity_inspected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='quantity_passed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='result',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('CONDITIONAL', 'Conditional Approval')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='inspected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='Quality score between 0 and 100.'),
        ),
        migrations.AddIndex(
            model_name='qualityinspection',
            index=models.Index(fields=['production_job', 'result'], name='qual_job_result_idx'),
        ),
        migrations.AddField(
            model_name='productiondefect',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='furniture.qualityinspection'),
        ),
        migrations.AddField(
            model_name='productiondefect',
            name='production_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_defects', to='furniture.productionjob'),
        ),
        migrations.AddField(
            model_name='productiondefect',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_quality_defects', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='productiondefect',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_quality_defects', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='reworkorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rework_orders', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='reworkorder',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_rework_orders', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='reworkorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rework_orders', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='reworkorder',
            name='defect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_orders', to='furniture.productiondefect'),
        ),
        migrations.AddField(
            model_name='reworkorder',
            name='production_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_orders', to='furniture.productionjob'),
        ),
        migrations.AddIndex(
            model_name='productiondefect',
            index=models.Index(fields=['production_job', 'status'], name='qual_defect_job_idx'),
        ),
    ]
