# Generated by Django 6.0.5 on 2026-07-20 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0017_productiondefect_reworkorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('center_type', models.CharField(choices=[('CUTTING', 'Cutting'), ('ASSEMBLY', 'Assembly'), ('SANDING', 'Sanding'), ('PAINTING', 'Painting'), ('UPHOLSTERY', 'Upholstery'), ('PACKAGING', 'Packaging'), ('CUSTOM', 'Custom')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('capacity_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('efficiency', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='machineusagelog',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='furniture.workcenter'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='furniture.workcenter'),
        ),
    ]
