# Generated by Django 6.0.5 on 2026-07-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0018_workcenter_machineusagelog_work_center_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionoutput',
            options={'ordering': ['-produced_at']},
        ),
    ]
