# Generated by Django 6.0.5 on 2026-08-27 11:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_department_business_unit'),
        ('furniture', '0022_normalize_stock_reservation_status'),
        ('inventory', '0009_alter_category_options_alter_product_options_and_more'),
        ('orders', '0009_order_integrity_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('default_wastage_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('overhead_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('target_profit_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross margin percentage on recommended selling price.', max_digits=6)),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('machine_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('additional_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('direct_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('estimated_total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('estimated_cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('recommended_selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('expected_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('assumptions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture_production_plan', to='orders.order')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_production_plans', to='Employee.employee')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='furniture_production_plans', to='inventory.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_production_plans', to='Employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('approve_productionplan', 'Can approve furniture production plans')],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlanAdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('TRANSPORT', 'Transport'), ('PACKAGING', 'Packaging'), ('SUBCONTRACT', 'Subcontract'), ('ENERGY', 'Energy / Utilities'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_cost_lines', to='furniture.productionplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlanLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=120)),
                ('hours_per_unit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('estimated_hours', models.DecimalField(decimal_places=4, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_lines', to='furniture.productionplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlanMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_unit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('estimated_hours', models.DecimalField(decimal_places=4, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plan_lines', to='inventory.asset')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_lines', to='furniture.productionplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlanMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('wastage_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use plan default wastage.', max_digits=6, null=True)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('estimated_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='furniture.productionplan')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plan_lines', to='inventory.rawmaterial')),
            ],
            options={
                'ordering': ['raw_material__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionplan',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='furn_plan_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='productionplan',
            constraint=models.CheckConstraint(condition=models.Q(('default_wastage_rate__gte', 0)), name='furn_plan_wastage_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionplan',
            constraint=models.CheckConstraint(condition=models.Q(('overhead_rate__gte', 0)), name='furn_plan_overhead_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionplan',
            constraint=models.CheckConstraint(condition=models.Q(('target_profit_margin__gte', 0), ('target_profit_margin__lt', 100)), name='furn_plan_margin_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='productionplanadditionalcost',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='furn_plan_additional_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionplanlabour',
            constraint=models.CheckConstraint(condition=models.Q(('hours_per_unit__gt', 0)), name='furn_plan_labour_hours_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='productionplanlabour',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_rate__gte', 0)), name='furn_plan_labour_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionplanmachine',
            constraint=models.CheckConstraint(condition=models.Q(('hours_per_unit__gt', 0)), name='furn_plan_machine_hours_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='productionplanmachine',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_cost__gte', 0)), name='furn_plan_machine_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionplanmaterial',
            constraint=models.UniqueConstraint(fields=('plan', 'raw_material'), name='unique_material_per_production_plan'),
        ),
        migrations.AddConstraint(
            model_name='productionplanmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_per_unit__gt', 0)), name='furn_plan_material_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='productionplanmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('wastage_rate__isnull', True), ('wastage_rate__gte', 0), _connector='OR'), name='furn_plan_material_waste_nonnegative'),
        ),
    ]
