# Generated by Django 6.0.5 on 2026-08-27 13:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0023_productionplan_productionplanadditionalcost_and_more'),
        ('orders', '0009_order_integrity_constraints'),
        ('sales', '0007_enterprise_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='sales_quotation_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_production_plan', to='sales.salesquotationitem'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture_production_plans', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='target_profit_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross margin percentage on recommended selling price.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='productionplanmaterial',
            name='wastage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use plan default wastage.', max_digits=6, null=True),
        ),
    ]
