# Generated by Django 6.0.5 on 2026-08-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0024_productionplan_sales_quotation_item_and_more'),
        ('inventory', '0009_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionoutput',
            name='inventory_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture_finished_output', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='inventory_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='inventory_released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture_outputs_released_to_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionjob',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft / Design'), ('DESIGN', 'Design'), ('COSTING', 'Costing / BOM'), ('QUOTATION', 'Quotation'), ('APPROVED', 'Approved'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('PRODUCTION_PLAN', 'Production Plan'), ('FUNDING_CHECK', 'Funding Check'), ('MATERIAL_RESERVED', 'Material Reserved'), ('IN_PRODUCTION', 'In Production'), ('QUALITY_CHECK', 'Quality Check'), ('READY_FOR_FINISHED_GOODS', 'Ready for Finished Goods'), ('FINISHED_GOODS', 'Finished Goods'), ('DELIVERED', 'Delivered'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='QUOTATION', max_length=30),
        ),
    ]
