# Generated by Django 6.0.5 on 2026-07-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlineproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='onlineproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecommerce/products/'),
        ),
        migrations.AddField(
            model_name='onlineproduct',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='onlineproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='onlineproduct',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
