# Generated by Django 6.0.5 on 2026-07-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_onlineproduct_options_onlineproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlineproduct',
            options={},
        ),
        migrations.RemoveField(
            model_name='onlineproduct',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='onlineproduct',
            name='updated_at',
        ),
    ]
