# Generated by Django 6.0.5 on 2026-07-29 19:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_onlineproduct_options_and_more'),
        ('inventory', '0009_alter_category_options_alter_product_options_and_more'),
        ('orders', '0004_alter_order_order_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ORDERED', 'Orders Created'), ('PARTIAL', 'Partially Completed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('cell', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('delivery_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EcommerceCheckoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_unit', models.CharField(choices=[('FURNITURE', 'Furniture & Manufacturing'), ('CONSTRUCTION', 'Construction'), ('AGRICULTURE', 'Agriculture / Poultry'), ('MARKETPLACE', 'Marketplace')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['checkout_id', 'business_unit'],
            },
        ),
        migrations.AlterModelOptions(
            name='onlineproduct',
            options={'ordering': ['product__business_unit', 'product__name']},
        ),
        migrations.RemoveField(
            model_name='onlineproduct',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='onlineproduct',
            name='is_published',
        ),
        migrations.AddField(
            model_name='onlineproduct',
            name='maximum_order_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='onlineproduct',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='onlineproduct',
            name='purchase_mode',
            field=models.CharField(choices=[('ADD_TO_CART', 'Add to Cart'), ('REQUEST_QUOTE', 'Request Quotation'), ('MADE_TO_ORDER', 'Made to Order')], db_index=True, default='ADD_TO_CART', max_length=30),
        ),
        migrations.AddField(
            model_name='onlineproduct',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='onlineproduct',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='onlineproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlineproduct',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional ecommerce hero image. Inventory image is the fallback.', null=True, upload_to='ecommerce/products/'),
        ),
        migrations.AlterField(
            model_name='onlineproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='online_product', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='onlineproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddIndex(
            model_name='onlineproduct',
            index=models.Index(fields=['purchase_mode'], name='ecom_online_mode_idx'),
        ),
        migrations.AddField(
            model_name='ecommercecheckout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_checkouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecommercecheckoutorder',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_orders', to='ecommerce.ecommercecheckout'),
        ),
        migrations.AddField(
            model_name='ecommercecheckoutorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ecommerce_checkout_link', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='ecommercecheckout',
            index=models.Index(fields=['user', 'status'], name='ecom_chk_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ecommercecheckout',
            index=models.Index(fields=['status', 'created_at'], name='ecom_chk_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='ecommercecheckout',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='ecom_checkout_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='ecommercecheckout',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='ecom_checkout_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='ecommercecheckout',
            constraint=models.CheckConstraint(condition=models.Q(('tax__gte', 0)), name='ecom_checkout_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='ecommercecheckout',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='ecom_checkout_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='ecommercecheckoutorder',
            constraint=models.UniqueConstraint(fields=('checkout', 'business_unit'), name='ecom_unique_order_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='ecommercecheckoutorder',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ecom_checkout_order_amount_nonnegative'),
        ),
    ]
