# Generated by Django 6.0.5 on 2026-07-31 12:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_ecommercecheckout_ecommercecheckoutorder_and_more'),
        ('finance', '0005_journalentry_customeradvance_ledgeraccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommercePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, max_length=60, unique=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Awaiting Confirmation'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='INITIATED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('customer_reference', models.CharField(blank=True, help_text='Phone number, bank reference or customer-facing receipt.', max_length=120)),
                ('idempotency_key', models.CharField(blank=True, help_text='Prevents a provider callback from being processed twice.', max_length=180, null=True, unique=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='ecommerce/payment_proofs/')),
                ('notes', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ecommerce.ecommercecheckout')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_ecommerce_payments', to=settings.AUTH_USER_MODEL)),
                ('customer_advance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecommerce_payment', to='finance.customeradvance')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_ecommerce_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at', '-pk'],
                'indexes': [models.Index(fields=['checkout', 'status'], name='ecom_pay_checkout_status_idx'), models.Index(fields=['provider', 'provider_reference'], name='ecom_pay_provider_ref_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ecom_payment_amount_positive'), models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('checkout',), name='ecom_one_confirmed_payment_per_checkout')],
            },
        ),
    ]
