# Generated by Django 6.0.5 on 2026-08-02 19:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
        ('ecommerce', '0005_ecommercepayment'),
        ('finance', '0005_journalentry_customeradvance_ledgeraccount_and_more'),
        ('orders', '0004_alter_order_order_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('seller_type', models.CharField(choices=[('WPG_INTERNAL', 'WPG-owned business'), ('INDEPENDENT', 'Independent seller')], db_index=True, default='INDEPENDENT', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=180)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage retained by WPG on independent-seller sales.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marketplace_sellers', to=settings.AUTH_USER_MODEL)),
                ('payable_account', models.ForeignKey(blank=True, help_text='Seller Payable control/sub-ledger account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_sellers', to='finance.ledgeraccount')),
                ('poultry_farm', models.OneToOneField(blank=True, help_text='Optional farm represented by this seller account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_seller', to='agriculture.poultryfarm')),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_code', models.CharField(max_length=40)),
                ('seller_name', models.CharField(max_length=180)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('seller_net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('settlement_status', models.CharField(choices=[('UNSETTLED', 'Unsettled'), ('ELIGIBLE', 'Eligible for settlement'), ('SETTLED', 'Settled'), ('REVERSED', 'Reversed')], db_index=True, default='UNSETTLED', max_length=20)),
                ('eligible_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_order_lines', to='agriculture.poultryfarm')),
                ('online_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_order_lines', to='ecommerce.onlineproduct')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_line', to='orders.orderitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='ecommerce.marketplaceseller')),
            ],
            options={
                'ordering': ['order_item__order_id', 'order_item_id'],
            },
        ),
        migrations.CreateModel(
            name='SellerProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Leave empty to use the seller's default commission rate.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('online_product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='seller_assignment', to='ecommerce.onlineproduct')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_assignments', to='ecommerce.marketplaceseller')),
            ],
            options={
                'ordering': ['online_product_id'],
            },
        ),
        migrations.CreateModel(
            name='SellerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_number', models.CharField(blank=True, max_length=60, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_seller_settlements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seller_settlements', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_settlement', to='finance.journalentry')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_seller_settlements', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='ecommerce.marketplaceseller')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SellerSettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketplace_order_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_line', to='ecommerce.marketplaceorderline')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ecommerce.sellersettlement')),
            ],
            options={
                'ordering': ['settlement_id', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceseller',
            index=models.Index(fields=['seller_type', 'is_active'], name='ecom_seller_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorderline',
            index=models.Index(fields=['seller', 'settlement_status'], name='ecom_line_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorderline',
            index=models.Index(fields=['farm', 'settlement_status'], name='ecom_line_farm_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ecom_market_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ecom_market_line_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorderline',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0)), name='ecom_market_line_gross_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorderline',
            constraint=models.CheckConstraint(condition=models.Q(('commission_amount__gte', 0)), name='ecom_market_line_comm_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorderline',
            constraint=models.CheckConstraint(condition=models.Q(('seller_net_amount__gte', 0)), name='ecom_market_line_net_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='sellerproductassignment',
            index=models.Index(fields=['seller', 'is_active'], name='ecom_assignment_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='sellersettlement',
            index=models.Index(fields=['seller', 'status'], name='ecom_settle_seller_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('total_gross__gte', 0)), name='ecom_settle_gross_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('total_commission__gte', 0)), name='ecom_settle_comm_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('total_payable__gte', 0)), name='ecom_settle_payable_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlementline',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0)), name='ecom_settle_line_gross_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlementline',
            constraint=models.CheckConstraint(condition=models.Q(('commission_amount__gte', 0)), name='ecom_settle_line_comm_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlementline',
            constraint=models.CheckConstraint(condition=models.Q(('payable_amount__gte', 0)), name='ecom_settle_line_pay_nonnegative'),
        ),
    ]
