# Generated by Django 6.0.5 on 2026-08-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_marketplaceseller_marketplaceorderline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceseller',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True),
        ),
    ]
