# Generated by Django 6.0.5 on 2026-08-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_marketplaceseller_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceorderline',
            name='settlement_status',
            field=models.CharField(choices=[('UNSETTLED', 'Unsettled'), ('ELIGIBLE', 'Eligible for settlement'), ('IN_SETTLEMENT', 'Included in settlement'), ('SETTLED', 'Settled'), ('REVERSED', 'Reversed')], db_index=True, default='UNSETTLED', max_length=20),
        ),
    ]
