# Generated by Django 6.0.5 on 2026-08-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_marketplaceorderline_settlement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercepayment',
            name='callback_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecommercepayment',
            name='last_status_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecommercepayment',
            name='provider_request_id',
            field=models.CharField(blank=True, db_index=True, help_text='Transaction/request identifier assigned when the payment is sent to the payment provider.', max_length=120),
        ),
        migrations.AddField(
            model_name='ecommercepayment',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict, help_text='Latest non-sensitive provider response used for payment reconciliation and audit.'),
        ),
        migrations.AddField(
            model_name='ecommercepayment',
            name='provider_status',
            field=models.CharField(blank=True, db_index=True, help_text='Latest raw status returned by the payment provider.', max_length=50),
        ),
    ]
