# Generated by Django 6.0.5 on 2026-08-06 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_ecommercepayment_callback_received_at_and_more'),
        ('finance', '0005_journalentry_customeradvance_ledgeraccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercepayment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Visa / Mastercard'), ('EKASH', 'eKash')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='PaymentProviderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MTN_MOMO', 'MTN MoMo'), ('AIRTEL_MONEY', 'Airtel Money'), ('RSWITCH_CARD', 'Visa / Mastercard via RSwitch'), ('EKASH', 'eKash / RNDPS')], max_length=40, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecommerce_payment_providers', to='finance.account')),
            ],
            options={
                'ordering': ['sort_order', 'provider'],
            },
        ),
    ]
