# Generated by Django 6.0.5 on 2026-06-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_department_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
    ]
