# Generated by Django 6.0.5 on 2026-06-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_remove_position_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
