# Generated by Django 6.0.5 on 2026-06-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_alter_employee_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
    ]
