"""
System-wide policy for internal identifier codes.

Policy:
- Internal system codes are generated by WPG BOS, never typed by users.
- Existing codes are preserved.
- ModelForms keep the field internally only as a disabled HiddenInput so
  legacy/custom form code that references self.fields["code"] does not break.
- Missing codes are filled immediately before model persistence.
- External/reference identifiers (TIN, national ID, invoice/reference numbers,
  barcodes, etc.) are intentionally outside this policy.
"""

from __future__ import annotations

import re
import secrets

from django import forms
from django.apps import apps
from django.db.models import CharField
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.forms.models import BaseModelForm


# Explicit internal identifiers already present in WPG BOS.
_EXPLICIT_INTERNAL_CODE_FIELDS = {
    "code",
    "product_code",
    "asset_code",
    "employee_code",
}

# These are business/external identifiers and must remain user/service supplied.
_EXTERNAL_OR_REFERENCE_TOKENS = {
    "barcode",
    "country",
    "currency",
    "external",
    "invoice",
    "national",
    "postal",
    "reference",
    "ref",
    "swift",
    "tax",
    "tin",
    "vat",
}

# Stable readable prefixes for key WPG domains. Unlisted models receive a
# deterministic prefix based on app + model name.
_PREFIXES = {
    "inventory.warehouse": "WH",
    "inventory.rawmaterial": "MAT",
    "inventory.product": "PRD",
    "inventory.asset": "AST",
    "employee.department": "DEP",
    "employee.employee": "EMP",
    "agriculture.poultryfarm": "AGR-FRM",
    "agriculture.poultryhouse": "AGR-HSE",
    "agriculture.poultrybreed": "AGR-BRD",
    "agriculture.poultryflock": "AGR-FLK",
    "agriculture.agricultureoperation": "AGR-OPR",
}


def _normalise_label(model) -> str:
    return f"{model._meta.app_label}.{model._meta.model_name}".lower()


def is_internal_code_field(model_field) -> bool:
    """Return True only for model-backed internal identifier fields."""
    if not isinstance(model_field, CharField):
        return False

    name = model_field.name.lower()

    if name in _EXPLICIT_INTERNAL_CODE_FIELDS:
        return True

    if not name.endswith("_code"):
        return False

    if any(token in name for token in _EXTERNAL_OR_REFERENCE_TOKENS):
        return False

    # Suffix-style codes are treated as internal identifiers when they are
    # uniqueness-oriented or deliberately optional for generator-driven saves.
    return bool(getattr(model_field, "unique", False) or getattr(model_field, "blank", False))


def internal_code_fields_for_model(model):
    return [
        field
        for field in model._meta.concrete_fields
        if is_internal_code_field(field)
    ]


def iter_internal_code_fields():
    """Audit helper: yield every detected internal code field in installed apps."""
    for model in apps.get_models():
        for field in internal_code_fields_for_model(model):
            yield model, field


def _abbrev(value: str, width: int = 3) -> str:
    letters = re.sub(r"[^A-Za-z0-9]+", "", value or "").upper()
    return (letters[:width] or "WPG")


def code_prefix(instance, field_name: str) -> str:
    model = instance.__class__
    label = _normalise_label(model)

    explicit = _PREFIXES.get(label)
    if explicit:
        # A Product's business unit makes the identifier more informative.
        if label == "inventory.product":
            business_unit = getattr(instance, "business_unit", "") or ""
            bu_prefix = {
                "FURNITURE": "FUR",
                "CONSTRUCTION": "CON",
                "AGRICULTURE": "AGR",
                "MARKETPLACE": "MKT",
            }.get(str(business_unit).upper())
            if bu_prefix:
                return f"{bu_prefix}-PRD"
        return explicit

    app_prefix = _abbrev(model._meta.app_label, 3)
    model_prefix = _abbrev(model._meta.model_name, 3)
    return f"{app_prefix}-{model_prefix}"


def _candidate_code(instance, field) -> str:
    prefix = code_prefix(instance, field.name)
    # 8 random uppercase hex characters gives concurrency-safe generation
    # without MAX(id)+1 races and works identically on SQLite/PostgreSQL.
    suffix = secrets.token_hex(4).upper()

    max_length = getattr(field, "max_length", None)
    if max_length:
        available_prefix = max(max_length - len(suffix) - 1, 1)
        prefix = prefix[:available_prefix].rstrip("-")
        return f"{prefix}-{suffix}"[:max_length]

    return f"{prefix}-{suffix}"


def generate_unique_code(instance, field) -> str:
    model = instance.__class__

    for _ in range(25):
        candidate = _candidate_code(instance, field)
        qs = model._default_manager.filter(**{field.name: candidate})
        if getattr(instance, "pk", None):
            qs = qs.exclude(pk=instance.pk)
        if not qs.exists():
            return candidate

    raise RuntimeError(
        f"Could not generate a unique internal code for "
        f"{model._meta.label}.{field.name}"
    )


def assign_missing_internal_codes(instance) -> None:
    """
    Fill missing internal identifiers without overwriting existing values.

    Existing model/service generators remain authoritative: if they have already
    populated the field before Django emits pre_save, this function does nothing.
    """
    for field in internal_code_fields_for_model(instance.__class__):
        current = getattr(instance, field.name, None)
        if current not in (None, ""):
            continue
        setattr(instance, field.name, generate_unique_code(instance, field))


@receiver(pre_save, dispatch_uid="wpg_systemwide_internal_code_generation")
def populate_internal_codes_before_save(sender, instance, raw=False, **kwargs):
    if raw or not hasattr(sender, "_meta"):
        return
    if sender._meta.abstract or sender._meta.proxy:
        return
    assign_missing_internal_codes(instance)


_ORIGINAL_BASE_MODEL_FORM_INIT = None
_ORIGINAL_BASE_MODEL_FORM_ITER = None
_ORIGINAL_BASE_MODEL_FORM_VISIBLE_FIELDS = None


def install_model_form_code_policy() -> None:
    """
    Hide and lock internal codes on every Django ModelForm system-wide.

    We intentionally keep each field in self.fields as a disabled HiddenInput.
    This prevents KeyErrors in legacy/custom __init__ methods that still refer
    to the code field after super().__init__(), while making the field invisible
    and impossible for a submitted POST to override.
    """
    global _ORIGINAL_BASE_MODEL_FORM_INIT
    global _ORIGINAL_BASE_MODEL_FORM_ITER
    global _ORIGINAL_BASE_MODEL_FORM_VISIBLE_FIELDS

    if getattr(BaseModelForm, "_wpg_internal_code_policy_installed", False):
        return

    _ORIGINAL_BASE_MODEL_FORM_INIT = BaseModelForm.__init__
    _ORIGINAL_BASE_MODEL_FORM_ITER = BaseModelForm.__iter__
    _ORIGINAL_BASE_MODEL_FORM_VISIBLE_FIELDS = BaseModelForm.visible_fields

    def _wpg_init(self, *args, **kwargs):
        _ORIGINAL_BASE_MODEL_FORM_INIT(self, *args, **kwargs)

        model = getattr(getattr(self, "_meta", None), "model", None)
        if model is None:
            return

        for model_field in internal_code_fields_for_model(model):
            form_field = self.fields.get(model_field.name)
            if form_field is None:
                continue

            form_field.required = False
            form_field.disabled = True
            form_field.widget = forms.HiddenInput()
            form_field.help_text = ""

    def _internal_code_names(form):
        model = getattr(getattr(form, "_meta", None), "model", None)
        if model is None:
            return set()
        return {
            field.name
            for field in internal_code_fields_for_model(model)
        }

    def _wpg_iter(self):
        hidden_internal_names = _internal_code_names(self)
        for bound_field in _ORIGINAL_BASE_MODEL_FORM_ITER(self):
            if bound_field.name in hidden_internal_names:
                continue
            yield bound_field

    def _wpg_visible_fields(self):
        hidden_internal_names = _internal_code_names(self)
        return [
            bound_field
            for bound_field in _ORIGINAL_BASE_MODEL_FORM_VISIBLE_FIELDS(self)
            if bound_field.name not in hidden_internal_names
        ]

    BaseModelForm.__init__ = _wpg_init
    BaseModelForm.__iter__ = _wpg_iter
    BaseModelForm.visible_fields = _wpg_visible_fields
    BaseModelForm._wpg_internal_code_policy_installed = True


def audit_internal_code_policy():
    """Return structured audit rows for shell/tests/diagnostics."""
    rows = []
    for model, field in iter_internal_code_fields():
        rows.append(
            {
                "model": model._meta.label,
                "field": field.name,
                "unique": bool(getattr(field, "unique", False)),
                "blank": bool(getattr(field, "blank", False)),
                "max_length": getattr(field, "max_length", None),
                "prefix": code_prefix(model(), field.name),
            }
        )
    return rows
