# Generated by Django 6.0.5 on 2026-07-28 20:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0011_remove_leave_approved_leave_status_leave_updated_at'),
        ('inventory', '0009_alter_category_options_alter_product_options_and_more'),
        ('orders', '0004_alter_order_order_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoultryBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('breed_type', models.CharField(choices=[('LAYER', 'Layer'), ('BROILER', 'Broiler'), ('DUAL_PURPOSE', 'Dual Purpose'), ('LOCAL', 'Local / Indigenous'), ('BREEDER', 'Breeder')], max_length=20)),
                ('expected_laying_age_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expected_market_age_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgricultureOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('operation_type', models.CharField(choices=[('FLOCK_SETUP', 'Flock Setup'), ('EGG_PRODUCTION', 'Egg Production'), ('INCUBATION', 'Incubation and Hatching'), ('BROODING', 'Chick Brooding'), ('GROW_OUT', 'Bird Grow-out'), ('FEEDING', 'Feeding Programme'), ('HEALTH', 'Health and Vaccination'), ('RESTOCK', 'Inventory Restock'), ('ORDER_FULFILMENT', 'Customer Order Fulfilment'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Operational cost synchronized from Finance postings.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('finance_reference', models.CharField(blank=True, help_text='Correlation reference returned by the shared Finance Engine.', max_length=100)),
                ('finance_posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_agriculture_operations', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agriculture_operations', to='Employee.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agriculture_operations', to=settings.AUTH_USER_MODEL)),
                ('source_order', models.ForeignKey(blank=True, help_text='Enterprise order created by Sales, Ecommerce, POS, restock or another approved order source.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agriculture_operations', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('record_type', models.CharField(choices=[('VACCINATION', 'Vaccination'), ('TREATMENT', 'Treatment'), ('CHECKUP', 'Routine Check-up'), ('BIOSECURITY', 'Biosecurity'), ('OTHER', 'Other')], max_length=20)),
                ('condition_or_vaccine', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('birds_treated', models.PositiveIntegerField(default=0)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('veterinarian_or_provider', models.CharField(blank=True, max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('medicine_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poultry_health_records', to='inventory.product')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='agriculture.agricultureoperation')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poultry_health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PoultryFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_poultry_farms', to='Employee.employee')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Agriculture inventory store serving this farm.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poultry_farms', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='agricultureoperation',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='agriculture.poultryfarm'),
        ),
        migrations.CreateModel(
            name='PoultryFlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('purpose', models.CharField(choices=[('LAYERS', 'Egg Layers'), ('BROILERS', 'Meat / Broilers'), ('BREEDERS', 'Breeding Stock'), ('DUAL_PURPOSE', 'Dual Purpose'), ('CHICKS', 'Chicks')], max_length=20)),
                ('source', models.CharField(choices=[('HATCHED', 'Hatched Internally'), ('PURCHASED', 'Purchased'), ('TRANSFERRED', 'Transferred'), ('OTHER', 'Other')], default='PURCHASED', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('QUARANTINED', 'Quarantined'), ('SOLD', 'Sold'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('arrival_or_hatch_date', models.DateField()),
                ('initial_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_quantity', models.PositiveIntegerField(default=0)),
                ('average_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flocks', to='agriculture.poultrybreed')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flocks', to='agriculture.poultryfarm')),
                ('livestock_product', models.ForeignKey(blank=True, help_text='Shared Inventory livestock product representing birds in this flock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poultry_flocks', to='inventory.product')),
                ('source_operation', models.ForeignKey(blank=True, help_text='Approved Agriculture operation that created or acquired this flock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_flocks', to='agriculture.agricultureoperation')),
            ],
            options={
                'ordering': ['-arrival_or_hatch_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('suspected_cause', models.CharField(choices=[('DISEASE', 'Disease'), ('ACCIDENT', 'Accident'), ('PREDATOR', 'Predator'), ('HEAT_STRESS', 'Heat Stress'), ('COLD_STRESS', 'Cold Stress'), ('NUTRITION', 'Nutrition'), ('UNKNOWN', 'Unknown'), ('OTHER', 'Other')], default='UNKNOWN', max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('health_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortality_records', to='agriculture.healthrecord')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mortality_records', to='agriculture.agricultureoperation')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poultry_mortality_records', to=settings.AUTH_USER_MODEL)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mortality_records', to='agriculture.poultryflock')),
            ],
            options={
                'ordering': ['-record_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='IncubationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('eggs_set', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('set_date', models.DateField()),
                ('expected_hatch_date', models.DateField()),
                ('actual_hatch_date', models.DateField(blank=True, null=True)),
                ('eggs_candled', models.PositiveIntegerField(default=0)),
                ('fertile_eggs', models.PositiveIntegerField(default=0)),
                ('infertile_eggs', models.PositiveIntegerField(default=0)),
                ('chicks_hatched', models.PositiveIntegerField(default=0)),
                ('unhatched_eggs', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('SET', 'Eggs Set'), ('CANDLED', 'Candled'), ('HATCHING', 'Hatching'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('chick_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incubation_outputs', to='inventory.product')),
                ('incubator_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incubation_batches', to='inventory.asset')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incubation_batches', to='agriculture.agricultureoperation')),
                ('output_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incubation_outputs', to='inventory.warehouse')),
                ('stock_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incubation_output', to='inventory.stockmovement')),
                ('source_flock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incubation_batches', to='agriculture.poultryflock')),
            ],
            options={
                'ordering': ['-set_date', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='agriculture.poultryflock'),
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('feed_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poultry_feeding_records', to='inventory.product')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feeding_records', to='agriculture.agricultureoperation')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poultry_feeding_records', to=settings.AUTH_USER_MODEL)),
                ('stock_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feeding_record', to='inventory.stockmovement')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poultry_feeding_records', to='inventory.warehouse')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_records', to='agriculture.poultryflock')),
            ],
            options={
                'ordering': ['-record_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('eggs_collected', models.PositiveIntegerField()),
                ('saleable_eggs', models.PositiveIntegerField(default=0)),
                ('hatching_eggs', models.PositiveIntegerField(default=0)),
                ('cracked_eggs', models.PositiveIntegerField(default=0)),
                ('dirty_or_rejected_eggs', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('inventory_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_production_records', to='inventory.product')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_production_records', to='agriculture.agricultureoperation')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_production_records', to=settings.AUTH_USER_MODEL)),
                ('stock_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_production_record', to='inventory.stockmovement')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_production_records', to='inventory.warehouse')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_production_records', to='agriculture.poultryflock')),
            ],
            options={
                'ordering': ['-record_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DailyFlockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('opening_quantity', models.PositiveIntegerField()),
                ('additions', models.PositiveIntegerField(default=0)),
                ('transferred_in', models.PositiveIntegerField(default=0)),
                ('mortality', models.PositiveIntegerField(default=0)),
                ('culls', models.PositiveIntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('transferred_out', models.PositiveIntegerField(default=0)),
                ('closing_quantity', models.PositiveIntegerField()),
                ('average_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('notes', models.TextField(blank=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_flock_records', to='agriculture.agricultureoperation')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poultry_daily_records', to=settings.AUTH_USER_MODEL)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_records', to='agriculture.poultryflock')),
            ],
            options={
                'ordering': ['-record_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PoultryHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('house_type', models.CharField(choices=[('BROODER', 'Brooder House'), ('GROWER', 'Grower House'), ('LAYER', 'Layer House'), ('BROILER', 'Broiler House'), ('BREEDER', 'Breeder House'), ('QUARANTINE', 'Quarantine House'), ('OTHER', 'Other')], default='LAYER', max_length=20)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='houses', to='agriculture.poultryfarm')),
            ],
            options={
                'ordering': ['farm__name', 'code'],
            },
        ),
        migrations.AddField(
            model_name='poultryflock',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flocks', to='agriculture.poultryhouse'),
        ),
        migrations.AddIndex(
            model_name='agricultureoperation',
            index=models.Index(fields=['operation_type', 'status'], name='agri_operation_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agricultureoperation',
            index=models.Index(fields=['farm', 'status'], name='agri_operation_farm_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='agricultureoperation',
            constraint=models.CheckConstraint(condition=models.Q(('budget__gte', 0)), name='agri_operation_budget_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='agricultureoperation',
            constraint=models.CheckConstraint(condition=models.Q(('actual_cost__gte', 0)), name='agri_operation_cost_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='mortalityrecord',
            index=models.Index(fields=['flock', 'record_date'], name='agri_mortality_date_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['flock', 'record_type', 'record_date'], name='agri_health_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='feedingrecord',
            index=models.Index(fields=['flock', 'record_date'], name='agri_feed_flock_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='eggproduction',
            constraint=models.UniqueConstraint(fields=('flock', 'record_date'), name='agri_unique_egg_record_per_flock'),
        ),
        migrations.AddConstraint(
            model_name='dailyflockrecord',
            constraint=models.UniqueConstraint(fields=('flock', 'record_date'), name='agri_unique_daily_record_per_flock'),
        ),
        migrations.AddConstraint(
            model_name='poultryhouse',
            constraint=models.UniqueConstraint(fields=('farm', 'code'), name='agri_unique_house_code_per_farm'),
        ),
        migrations.AddIndex(
            model_name='poultryflock',
            index=models.Index(fields=['farm', 'status'], name='agri_flock_farm_status_idx'),
        ),
        migrations.AddIndex(
            model_name='poultryflock',
            index=models.Index(fields=['purpose', 'status'], name='agri_flock_purpose_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='poultryflock',
            constraint=models.CheckConstraint(condition=models.Q(('initial_quantity__gt', 0)), name='agri_flock_initial_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='poultryflock',
            constraint=models.CheckConstraint(condition=models.Q(('current_quantity__gte', 0)), name='agri_flock_current_qty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='poultryflock',
            constraint=models.CheckConstraint(condition=models.Q(('average_unit_cost__gte', 0)), name='agri_flock_unit_cost_nonnegative'),
        ),
    ]
