# Generated by Django 6.0.5 on 2026-06-11 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionmachine',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='productionmachine',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='product',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProductionLabour',
        ),
        migrations.DeleteModel(
            name='ProductionMachine',
        ),
        migrations.DeleteModel(
            name='ProductionOrder',
        ),
    ]
