# Generated by Django 6.0.5 on 2026-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_productionmachine_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive'), ('disposed', 'Disposed')], default='active', max_length=20),
        ),
    ]
