# Generated by Django 6.0.5 on 2026-06-14 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_employee_job_title'),
        ('inventory', '0003_rawmaterial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_use', 'In Use'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive'), ('disposed', 'Disposed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial'),
        ),
        migrations.DeleteModel(
            name='BillOfMaterial',
        ),
    ]
