# Generated by Django 6.0.5 on 2026-07-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_image_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business_unit',
            field=models.CharField(choices=[('FURNITURE', 'Furniture & Manufacturing'), ('CONSTRUCTION', 'Construction'), ('AGRICULTURE', 'Agriculture / Poultry'), ('MARKETPLACE', 'Marketplace')], default='FURNITURE', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical Product'), ('SERVICE', 'Service'), ('CUSTOM', 'Custom Product')], default='PHYSICAL', max_length=20),
        ),
    ]
