# Generated by Django 6.0.5 on 2026-07-26 18:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_remove_leave_approved_leave_status_leave_updated_at'),
        ('inventory', '0008_stockreservation'),
        ('orders', '0004_alter_order_order_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['business_unit', 'name']},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['warehouse_type', 'name']},
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_negative_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_products', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='product',
            name='standard_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='valuation_method',
            field=models.CharField(choices=[('STANDARD', 'Standard Cost'), ('WEIGHTED_AVERAGE', 'Weighted Average'), ('FIFO', 'FIFO')], default='STANDARD', max_length=30),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='linked_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_raw_material', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='business_unit',
            field=models.CharField(blank=True, choices=[('FURNITURE', 'Furniture & Manufacturing'), ('CONSTRUCTION', 'Construction'), ('AGRICULTURE', 'Agriculture / Poultry'), ('MARKETPLACE', 'Marketplace')], max_length=30),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('SALES_ORDER', 'Sales Order'), ('ECOMMERCE_ORDER', 'Ecommerce Order'), ('PRODUCTION_JOB', 'Furniture Production Job'), ('CONSTRUCTION_PROJECT', 'Construction Project'), ('AGRICULTURE_OPERATION', 'Agriculture Operation'), ('FEED_CONSUMPTION', 'Feed Consumption'), ('EGG_COLLECTION', 'Egg Collection'), ('INCUBATION', 'Incubation'), ('TRANSFER', 'Warehouse Transfer'), ('RETURN', 'Stock Return'), ('STOCK_COUNT', 'Stock Count'), ('ADJUSTMENT', 'Manual Adjustment'), ('OTHER', 'Other')], default='OTHER', max_length=40),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_movement', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed'), ('CANCELLED', 'Cancelled')], default='POSTED', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transfer_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='completed_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='allow_negative_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='business_unit',
            field=models.CharField(blank=True, choices=[('FURNITURE', 'Furniture & Manufacturing'), ('CONSTRUCTION', 'Construction'), ('AGRICULTURE', 'Agriculture / Poultry'), ('MARKETPLACE', 'Marketplace')], max_length=30),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('MAIN', 'Main Warehouse'), ('RAW_MATERIAL', 'Raw Material Store'), ('FINISHED_GOODS', 'Finished Goods Store'), ('PROJECT', 'Construction Project Store'), ('FARM', 'Agriculture / Farm Store'), ('SHOP', 'Shop / Marketplace Store'), ('TRANSIT', 'Transit Warehouse'), ('OTHER', 'Other')], default='MAIN', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('FINISHED_GOOD', 'Finished Good'), ('CONSUMABLE', 'Consumable'), ('AGRICULTURE_INPUT', 'Agriculture Input'), ('AGRICULTURE_OUTPUT', 'Agriculture Output'), ('LIVESTOCK', 'Livestock'), ('SERVICE', 'Service'), ('CUSTOM', 'Custom Product')], default='FINISHED_GOOD', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_stock_movements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT_IN', 'Positive Adjustment'), ('ADJUSTMENT_OUT', 'Negative Adjustment'), ('RETURN_IN', 'Return In'), ('RETURN_OUT', 'Return Out')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='raw_material',
            field=models.ForeignKey(blank=True, help_text='Legacy field. New movements should use product.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESERVED', 'Reserved'), ('PARTIAL', 'Partially Reserved'), ('FAILED', 'Failed'), ('RELEASED', 'Released'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'warehouse', 'movement_type'], name='inv_move_prod_wh_type_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inv_move_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['business_unit', 'created_at'], name='inv_move_unit_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['status', 'created_at'], name='inv_move_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='inventory_product_selling_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('standard_cost__gte', 0)), name='inventory_product_standard_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0)), name='inventory_product_reorder_level_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_quantity__gte', 0)), name='inventory_product_reorder_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_movement_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='inventory_movement_unit_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), ('raw_material__isnull', False), _connector='OR'), name='inventory_movement_requires_stock_item'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('completed_quantity__gte', 0)), name='inventory_reservation_completed_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('requested_quantity'))), name='inventory_reservation_reserved_not_above_requested'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('completed_quantity__lte', models.F('reserved_quantity'))), name='inventory_reservation_completed_not_above_reserved'),
        ),
    ]
