# Generated by Django 6.0.5 on 2026-07-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('ECOMMERCE', 'Ecommerce Order'), ('CUSTOM_FURNITURE', 'Custom Furniture Order'), ('RESTOCK', 'Restock Existing Product'), ('NEW_PRODUCT', 'New Product Development'), ('POS', 'Point of Sale')], max_length=30),
        ),
    ]
