# Generated by Django 6.0.5 on 2026-07-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business_unit',
            field=models.CharField(choices=[('FURNITURE', 'Furniture & Manufacturing'), ('CONSTRUCTION', 'Construction'), ('AGRICULTURE', 'Agriculture / Poultry'), ('MARKETPLACE', 'Marketplace')], default='FURNITURE', max_length=30),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='specifications',
            field=models.TextField(blank=True, help_text='Dimensions, materials, colour, design, location or other customer requirements.'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
