# Generated by Django 6.0.5 on 2026-07-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_business_unit_orderitem_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('ECOMMERCE', 'Ecommerce Order'), ('CUSTOM_FURNITURE', 'Custom Furniture Order'), ('CUSTOM_ORDER', 'Custom Order'), ('RESTOCK', 'Restock Existing Product'), ('NEW_PRODUCT', 'New Product Development'), ('POS', 'Point of Sale'), ('PROJECT', 'Project / Contract Order'), ('MAINTENANCE', 'Renovation / Maintenance Order')], max_length=30),
        ),
    ]
