# Generated by Django 6.0.5 on 2026-06-12 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0002_rename_client_project_client_name_and_more'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionexpense',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='constructionlabour',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='constructionmaterial',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
