# Generated by Django 6.0.5 on 2026-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0003_alter_constructionexpense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('ongoing', 'Ongoing'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='planning', max_length=20),
        ),
    ]
