# Generated by Django 6.0.5 on 2026-06-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0005_alter_constructionexpense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionmaterial',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
