# Generated by Django 6.0.5 on 2026-06-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_warehouse_rawmaterial_category_and_more'),
        ('sales', '0003_sale_discount_sale_sale_no_sale_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
    ]
