# Generated by Django 6.0.5 on 2026-07-23 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockreservation'),
        ('orders', '0004_alter_order_order_type'),
        ('sales', '0004_sale_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['company_name', 'full_name', 'phone']},
        ),
        migrations.AlterModelOptions(
            name='salesquotation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='salesquotationitem',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('INSTITUTION', 'Institution')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotations_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='business_unit',
            field=models.CharField(blank=True, choices=[('FURNITURE', 'Furniture & Manufacturing'), ('CONSTRUCTION', 'Construction'), ('AGRICULTURE', 'Agriculture / Poultry'), ('MARKETPLACE', 'Marketplace')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='converted_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_sales_quotation', to='orders.order'),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='order_type',
            field=models.CharField(blank=True, choices=[('ECOMMERCE', 'Ecommerce'), ('CUSTOM_FURNITURE', 'Custom Furniture'), ('RESTOCK', 'Restock'), ('NEW_PRODUCT', 'New Product Development'), ('POS', 'Point of Sale'), ('PROJECT', 'Construction Project'), ('CUSTOM_ORDER', 'Custom Order'), ('MAINTENANCE', 'Maintenance / Renovation')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotations_prepared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salesquotationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesquotationitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesquotationitem',
            name='specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesquotationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_sales', to='sales.salesquotation'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='quotation_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to Order'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesquotationitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotation_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='salesquotationitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesquotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
